# Community Analysis Notebook

## A notebook to explore the communities provided in the social/spatial comms csv
### Check what's up!

In [1]:
# Load in Libraries
import pandas as pd
import geopandas as gpd
import os
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
# data path
data_path = "../../data/raw/ind_comm/"

# First set our empty list
comm_pop_datasets = []

# For each file within our processed folder, listed by the listfunction 
for file in os.listdir(data_path):
    # if the filename is equal to wildcard.shp, i.e. has a .shp extension
    if file.endswith('.csv'):
        # we use the .append() function to append the file to our crime_rate_datasets list
        comm_pop_datasets.append(file)

print(comm_pop_datasets)

['community_0.csv', 'community_1.csv', 'community_10.csv', 'community_11.csv', 'community_12.csv', 'community_13.csv', 'community_14.csv', 'community_15.csv', 'community_16.csv', 'community_17.csv', 'community_18.csv', 'community_19.csv', 'community_2.csv', 'community_20.csv', 'community_21.csv', 'community_22.csv', 'community_23.csv', 'community_24.csv', 'community_25.csv', 'community_26.csv', 'community_27.csv', 'community_28.csv', 'community_29.csv', 'community_3.csv', 'community_30.csv', 'community_31.csv', 'community_32.csv', 'community_33.csv', 'community_34.csv', 'community_35.csv', 'community_36.csv', 'community_37.csv', 'community_38.csv', 'community_39.csv', 'community_4.csv', 'community_40.csv', 'community_41.csv', 'community_42.csv', 'community_43.csv', 'community_44.csv', 'community_45.csv', 'community_46.csv', 'community_47.csv', 'community_48.csv', 'community_49.csv', 'community_5.csv', 'community_50.csv', 'community_51.csv', 'community_52.csv', 'community_53.csv', 'community_6.csv', 'community_7.csv', 'community_8.csv', 'community_9.csv']

In [3]:
for comm in comm_pop_datasets:
    comm_df = pd.read_csv(data_path + comm)
    comm_nm = comm.split('.')[0]
    print(comm_nm + " : " + str(comm_df['count'].sum()))

community_0 : 194492
community_1 : 247790
community_10 : 116772
community_11 : 4935
community_12 : 13378
community_13 : 8401
community_14 : 28007
community_15 : 1121
community_16 : 1335
community_17 : 29366
community_18 : 4526
community_19 : 7917
community_2 : 183161
community_20 : 2188
community_21 : 5687
community_22 : 45
community_23 : 1287
community_24 : 1486
community_25 : 745
community_26 : 4138
community_27 : 888
community_28 : 778
community_29 : 1253
community_3 : 89166
community_30 : 17
community_31 : 40
community_32 : 6
community_33 : 38
community_34 : 144
community_35 : 31
community_36 : 16
community_37 : 49
community_38 : 61
community_39 : 5
community_4 : 6213
community_40 : 51
community_41 : 67
community_42 : 28
community_43 : 16
community_44 : 35
community_45 : 7
community_46 : 6
community_47 : 22
community_48 : 8
community_49 : 4
community_5 : 152562
community_50 : 9
community_51 : 38
community_52 : 4
community_53 : 6
community_6 : 184435
community_7 : 211398
community_8 : 60431
community_9 : 103387

In [4]:
for comm in comm_pop_datasets:
    comm_df = pd.read_csv(data_path + comm)
    comm_nm = comm.split('.')[0]
    print(str(comm_df['count'].sum()))

194492
247790
116772
4935
13378
8401
28007
1121
1335
29366
4526
7917
183161
2188
5687
45
1287
1486
745
4138
888
778
1253
89166
17
40
6
38
144
31
16
49
61
5
6213
51
67
28
16
35
7
6
22
8
4
152562
9
38
4
6
184435
211398
60431
103387

In [7]:
#List communities under 100 people
#For communities with under 100 people, how many towers are there?
comm_u100 = []

for comm in comm_pop_datasets:
        comm_df = pd.read_csv(data_path + comm)
        comm_nm = comm.split('.')[0]
        comm_size = comm_df['count'].sum()
        
        if comm_size < 100:
            comm_u100.append(comm_nm)
            print(comm_nm + ' : ' + str(len(comm_df['count']))+ " : " + str(comm_df['count'].sum()))
    
    #if comm_size < 100:
        #comm_u100.append(comm_nm)
        
#print(comm_u100)
len(comm_u100)

community_22 : 13 : 45
community_30 : 10 : 17
community_31 : 11 : 40
community_32 : 3 : 6
community_33 : 5 : 38
community_35 : 9 : 31
community_36 : 9 : 16
community_37 : 10 : 49
community_38 : 10 : 61
community_39 : 2 : 5
community_40 : 23 : 51
community_41 : 41 : 67
community_42 : 8 : 28
community_43 : 1 : 16
community_44 : 13 : 35
community_45 : 3 : 7
community_46 : 3 : 6
community_47 : 2 : 22
community_48 : 1 : 8
community_49 : 1 : 4
community_50 : 2 : 9
community_51 : 8 : 38
community_52 : 2 : 4
community_53 : 3 : 6

24

In [13]:
comm_grid = gpd.read_file('../../data/working_files/community_wpopulation/community_0_pop.shp')

comm_grid.head()

,Join_Count,TARGET_FID,OBJECTID,IID,Total_Pop,Pro_Pop,Shape_Leng,Shape_Area,Join_Cou_1,TARGET_F_1,OBJECTID_1,community,count,Comm_Pro,geometry
0,1,99,1,45,3.104452,0.000767,0.015043,1.245186e-05,1,0,100,0,1,0.000767,"POLYGON ((84.94134081142937 27.36573549569664,..."
1,1,99,2,275,0.000000,0.000000,0.000358,5.315712e-09,1,1,100,0,1,0.000000,"POLYGON ((85.02942947778826 27.36511717851505,..."
2,1,99,3,276,6.411810,0.001584,0.012110,6.270570e-06,1,2,100,0,1,0.001584,"POLYGON ((85.02934081092974 27.36511717851505,..."
3,1,99,4,265,60.482178,0.014940,0.014076,1.043345e-05,1,3,100,0,1,0.014940,"POLYGON ((85.02934081092974 27.36511717851505,..."
4,1,99,5,266,23.974487,0.005922,0.016000,1.600000e-05,1,4,100,0,1,0.005922,"POLYGON ((85.02534081082979 27.36511717851505,..."

In [15]:
comm_grid['Comm_Pro'].sum()

21293.00000000025

In [17]:
comm_grid_sort = comm_grid.sort_values(by=['Comm_Pro'], ascending=False)
comm_grid_sort.head()

,Join_Count,TARGET_FID,OBJECTID,IID,Total_Pop,Pro_Pop,Shape_Leng,Shape_Area,Join_Cou_1,TARGET_F_1,OBJECTID_1,community,count,Comm_Pro,geometry
43315,1,16,58128,62,496.017792,0.060210,0.015134,0.000015,1,58127,17,0,2065,124.334094,"POLYGON ((84.34134081082982 27.66368962287783,..."
43371,1,16,58184,54,397.864319,0.048296,0.016000,0.000016,1,58183,17,0,2065,99.730494,"POLYGON ((84.34134081082982 27.64511717831516,..."
18751,1,81,19035,7139,267.847931,0.028530,0.016000,0.000016,1,19034,82,0,3256,92.892293,"POLYGON ((84.68134081122952 28.15711717851502,..."
43351,1,16,58164,31,362.497498,0.044003,0.016000,0.000016,1,58163,17,0,2065,90.865285,"POLYGON ((84.33334081062998 27.64111717821527,..."
43363,1,16,58176,42,321.295776,0.039001,0.016000,0.000016,1,58175,17,0,2065,80.537472,"POLYGON ((84.33734081072987 27.64511717831516,..."

In [38]:
comm_columns = comm_grid_sort.columns.values
print(comm_columns)

[u'Join_Count' u'TARGET_FID' u'OBJECTID' u'IID' u'Total_Pop' u'Pro_Pop'
 u'Shape_Leng' u'Shape_Area' u'Join_Cou_1' u'TARGET_F_1' u'OBJECTID_1'
 u'community' u'count' u'Comm_Pro' 'geometry']

In [39]:
comm_comp = comm_grid_sort.drop(columns=['Join_Count', 'TARGET_FID', 'OBJECTID', 'IID', 'Total_Pop', 'Pro_Pop', 'Shape_Leng', 'Shape_Area', 'Join_Cou_1', 'TARGET_F_1', 'OBJECTID_1', 'community', 'count'])

comm_comp.head()

         Comm_Pro                                           geometry
43315  124.334094  POLYGON ((84.34134081082982 27.66368962287783,...
43371   99.730494  POLYGON ((84.34134081082982 27.64511717831516,...
18751   92.892293  POLYGON ((84.68134081122952 28.15711717851502,...
43351   90.865285  POLYGON ((84.33334081062998 27.64111717821527,...
43363   80.537472  POLYGON ((84.33734081072987 27.64511717831516,...

In [40]:
comm_comp.insert(1, 'Comm_Per', 0)
comm_comp.head()

         Comm_Pro  Comm_Per                                           geometry
43315  124.334094         0  POLYGON ((84.34134081082982 27.66368962287783,...
43371   99.730494         0  POLYGON ((84.34134081082982 27.64511717831516,...
18751   92.892293         0  POLYGON ((84.68134081122952 28.15711717851502,...
43351   90.865285         0  POLYGON ((84.33334081062998 27.64111717821527,...
43363   80.537472         0  POLYGON ((84.33734081072987 27.64511717831516,...

In [43]:
total_comm_pop = comm_comp['Comm_Pro'].sum()
print(total_comm_pop)

21293.00000000025

In [52]:
comm_comp['Comm_Per'] = comm_comp["Comm_Pro"].cumsum()

In [54]:
comm_comp.insert(1, 'Comm_Perc', 0)

for row in range(len(comm_comp['Comm_Perc'])):
    comm_comp.loc[row, 'Comm_Perc'] = (comm_comp.loc[row, 'Comm_Per']/total_comm_pop) * 100

comm_comp.head()

,Comm_Pro,Comm_Perc,Comm_Per,geometry
43315,124.334094,0.583920,124.334094,"POLYGON ((84.34134081082982 27.66368962287783,..."
43371,99.730494,1.052292,224.064588,"POLYGON ((84.34134081082982 27.64511717831516,..."
18751,92.892293,1.488550,316.956882,"POLYGON ((84.68134081122952 28.15711717851502,..."
43351,90.865285,1.915287,407.822166,"POLYGON ((84.33334081062998 27.64111717821527,..."
43363,80.537472,2.293522,488.359639,"POLYGON ((84.33734081072987 27.64511717831516,..."

In [27]:
comm_grid_sort['Comm_Pro'].plot